import { StyleSheet } from "react-native";
import { font1, font2, font3, varTextColor, varGray1, varTextSecondaryColor } from "./styles";

const fontsizeHeader = 16; // figma says 12.456??
//spacing is also a little weird in the header with the fonts rn

export const articleStyles = StyleSheet.create({
  image: {
    width: "100%",
    height: 253,
  },
  mediaCaption: {
    color: varGray1,
    fontFamily: font1,
    fontSize: fontsizeHeader-2,
    fontStyle: "normal",
    fontWeight: "400",
    marginTop: 12,
    marginBottom: 22,
  },
  headingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 7.422,
    marginBottom: 27,
  },
  title: {
    // alignSelf: "stretch",
    color: varTextColor,
    fontFamily: font1,
    fontSize: 24,
    fontWeight: "700",
  },
  lead: {
    // alignSelf: "stretch",
    color: varTextSecondaryColor,
    fontFamily: font1,
    fontSize: fontsizeHeader,
    fontStyle: "italic",
    fontWeight: "400",
  },
  author: {
    color: varTextSecondaryColor,
    fontFamily: font2,
    fontSize: fontsizeHeader,
    fontWeight: "700",
  },
  publishedDetails: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14.845,
    // alignSelf: "stretch",
  },
  publishedDetailsText: {
    color: varGray1,
    fontFamily: font3,
    fontSize: fontsizeHeader,
    fontWeight: "400",
  },
  articleBodyWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  articleBody: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 36,
    paddingBottom: 10,
  },
  text: {
    color: varTextColor,
    fontFamily: font1,
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 24,
    width: "98%",
  },
  hyperlink: {
    color: varTextColor,
    fontFamily: font1,
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 24,
    textDecorationLine: "underline",
  },
  correction: {
    color: varTextColor,
    fontFamily: font1,
    fontSize: 18,
    fontStyle: "italic",
    fontWeight: "400",
    lineHeight: 24,
  },
  advert: {
    width: "auto",
    height: 280,
    flexShrink: 0,
    backgroundColor: "#F3F3F3",
    paddingTop: 36,
    paddingRight: 50,
    paddingBottom: 55,
    paddingLeft: 48,
  },
  adImage: {
    display: "flex",
    width: 292,
    height: 190,
    paddingTop: 65.219,
    paddingBottom: 63.457,
    paddingRight: 146.282,
    paddingLeft: 150.393,
    justifyContent: "flex-end",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#C9C9C9",
  },
  adAuthor: {
    color: varGray1,
    fontFamily: font1,
    fontSize: fontsizeHeader,
    fontStyle: "normal",
    fontWeight: "400",
    textAlign: "center",
    // lineHeight: "normal",
  },
  readMoreHeading: {
    color: varTextColor,
    fontFamily: font2,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "600",
    // lineHeight: "normal",
    textTransform: "uppercase",
    marginBottom: 16,
  },
  actionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: "#FFF",
    width: "100%",
    padding: 18,
    justifyContent: "space-between",
    alignItems: "flex-start",
    height: 64,
    borderTopWidth: 1,
    borderColor: "#eee",
  },
    actions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 10,
  },
  icon: {
    width: 24,
    height: 24,
  },
});
