import { StyleSheet } from "react-native";
import { font1, font2, font3 } from "./styles";

export const articleStyles = StyleSheet.create({
  container: {
    padding: 16,
    width: 390,
    backgroundColor: "#FFF",
    // height: 5849,
  },
  image: {
    display: "flex",
    width: "100%",
    height: 253,
    flex: 1,
    paddingLeft: 162.282,
    paddingRight: 166.393,
    justifyContent: "flex-end",
    alignItems: "center",
    flexGrow: 0,
  },
  mediaDetails: {
    display: "flex",
    flexDirection: "column", // had to change from row to column, wasn't fitting
    alignItems: "flex-start",
    // gap: 11.134,
    marginBottom: 22,
  },
  mediaCaption: {
    color: "#9E9E9E",
    fontFamily: font1,
    fontSize: 12.456,
    fontStyle: "normal",
    fontWeight: "400",
    // lineHeight: "normal",
  },
  mediaAuthor: {
    color: "#9E9E9E",
    fontFamily: font1,
    fontSize: 12.456,
    fontStyle: "italic", // changed from normal to italic
    fontWeight: "400",
    // lineHeight: "normal",
  },
  articleHeading: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 7.422,
    marginBottom: 27,
  },
  title: {
    alignSelf: "stretch",
    color: "#000",
    fontFamily: font1,
    fontSize: 24,
    fontStyle: "normal",
    fontWeight: "700",
    // lineHeight: "normal",
  },
  lead: {
    alignSelf: "stretch",
    color: "#9E9E9E",
    fontFamily: font1,
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "400",
    // lineHeight: "normal",
  },
  author: {
    color: "#000",
    fontFamily: font2,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "700",
    // lineHeight: "normal",
  },
  publishedDetails: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14.845,
    alignSelf: "stretch",
  },
  publishedDate: {
    color: "#9E9E9E",
    fontFamily: font3,
    fontSize: 12.456,
    fontStyle: "normal",
    fontWeight: "400",
    // lineHeight: "normal",
  },
  section: {
    color: "#9E9E9E",
    fontFamily: font3,
    fontSize: 12.456,
    fontStyle: "normal",
    fontWeight: "400",
    // lineHeight: "normal",
  },
  articleBodyWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  articleBody: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 36,
  },
  text: {
    color: "#000",
    fontFamily: font1,
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 24,
  },
  hyperlink: {
    color: "#000",
    fontFamily: font1,
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 24,
    textDecorationLine: "underline",
  },
  correction: {
    color: "#000",
    fontFamily: font1,
    fontSize: 14,
    fontStyle: "italic",
    fontWeight: "400",
    lineHeight: 24,
  },
  advert: {
    width: "auto",
    height: 280,
    flexShrink: 0,
    backgroundColor: "#F3F3F3",
    paddingTop: 36,
    paddingRight: 50,
    paddingBottom: 55,
    paddingLeft: 48,
  },
  adImage: {
    display: "flex",
    width: 292,
    height: 190,
    paddingTop: 65.219,
    paddingBottom: 63.457,
    paddingRight: 146.282,
    paddingLeft: 150.393,
    justifyContent: "flex-end",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#C9C9C9",
  },
  adAuthor: {
    color: "#9E9E9E",
    fontFamily: font1,
    fontSize: 12.456,
    fontStyle: "normal",
    fontWeight: "400",
    // lineHeight: "normal",
  },
  readMoreHeading: {
    color: "#000",
    fontFamily: font2,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "600",
    // lineHeight: "normal",
    textTransform: "uppercase",
    marginBottom: 16,
  },
  actionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: "#FFF",
    width: 390,
    padding: 16,
    justifyContent: "flex-end",
    alignItems: "flex-start",
    height: 58,
    gap: 235,
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 10,
  },
  icon: {
    width: 24,
    height: 24,
  },
});
