import { StyleSheet } from "react-native";
import {
  font1,
  font2,
  font3,
  varGray1,
  varTextColor,
  varTextSecondaryColor,
} from "./styles";

const fontsizeHeader = 16; // figma says 12.456??
//spacing is also a little weird in the header with the fonts rn

export const articleStyles = StyleSheet.create({
  image: {
    width: "100%",
    height: 253,
  },
  mediaCaption: {
    color: varGray1,
    fontFamily: font1,
    fontSize: fontsizeHeader - 2,
    fontStyle: "normal",
    fontWeight: "400",
    marginTop: 12,
    marginBottom: 22,
    alignSelf: "flex-start",
    marginLeft: -15,
  },
  headingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 7.422,
    marginBottom: 27,
    paddingTop: 25,
  },
  title: {
    // alignSelf: "stretch",
    color: varTextColor,
    fontFamily: font1,
    fontSize: 26,
    fontWeight: "700",
  },
  lead: {
    // alignSelf: "stretch",
    color: varTextSecondaryColor,
    fontFamily: font1,
    fontSize: fontsizeHeader,
    fontStyle: "italic",
    fontWeight: "400",
  },
  author: {
    color: varTextSecondaryColor,
    fontFamily: font2,
    fontSize: fontsizeHeader,
    fontWeight: "700",
  },
  publishedDetails: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14.845,
    // alignSelf: "stretch",
  },
  publishedDetailsText: {
    color: varGray1,
    fontFamily: font3,
    fontSize: fontsizeHeader,
    fontWeight: "400",
  },
  articleBodyWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    marginTop: 3,
  },
  articleBody: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingBottom: 10,
    marginLeft: -3,
  },
  text: {
    color: varTextColor,
    fontFamily: font1,
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 24,
    width: "98%",
  },
  hyperlink: {
    color: varTextColor,
    fontFamily: font1,
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 24,
    textDecorationLine: "underline",
  },
  correction: {
    color: varTextColor,
    fontFamily: font1,
    fontSize: 18,
    fontStyle: "italic",
    fontWeight: "400",
    lineHeight: 24,
  },
  advert: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    // height: 300,
    flexShrink: 0,
    backgroundColor: "#F3F3F3",
<<<<<<< HEAD
    paddingVertical: "5%",
    paddingRight: 50,
=======
    paddingTop: "2%",
    paddingBottom: "5%",
    paddingRight: 48,
>>>>>>> e481223bbba4271bc6fd087b618c40700b3d6db4
    paddingLeft: 48,
  },
  adImage: {
    display: "flex",
    width: 292,
    // height: 190,
    // paddingTop: 65.219,
    // paddingBottom: 63.457,
    // paddingRight: 146.282,
    // paddingLeft: 150.393,
    justifyContent: "flex-end",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#C9C9C9",
  },
  adText: {
    color: varGray1,
    fontFamily: font1,
    fontSize: fontsizeHeader,
    fontStyle: "normal",
    fontWeight: "400",
    textAlign: "center",

    // paddingTop: "5%",
    paddingBottom: 10,
    // lineHeight: "normal",
  },
  readMoreHeading: {
    color: varTextColor,
    fontFamily: font2,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "600",
    // lineHeight: "normal",
    textTransform: "uppercase",
    marginBottom: 16,
  },
  actionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: "#FFF",
    width: "100%",
    padding: 18,
    justifyContent: "space-between",
    alignItems: "flex-start",
<<<<<<< HEAD
    height: 70,
=======
    height: 65,
>>>>>>> e481223bbba4271bc6fd087b618c40700b3d6db4
    borderTopWidth: 1,
    borderColor: "#eee",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 30,
    paddingHorizontal: 5,
  },
  icon: {
<<<<<<< HEAD
    width: 28,
    height: 28,
=======
    width: 26,
    height: 26,
>>>>>>> e481223bbba4271bc6fd087b618c40700b3d6db4
  },
});
