name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./nms

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔄 Install dependencies
        run: npm install

      - name: 🧹 Run Linter
        run: npm run lint

      - name: 🛠️ Run Build
        run: npm run build