import { Article } from "src/types/types";

export const dummyData: Article[] = [
  {
    id: "35711",
    uuid: "aa6fa322-9c4d-4dc1-9850-cb83dd5f3f88",
    slug: "niyanta-nepal-25-elected-ucs-president-on-pro-divestment-platform",
    seo_title: null,
    seo_description: null,
    seo_image: null,
    headline:
      "Niyanta Nepal \u201925 elected UCS president on pro-divestment platform",
    subhead:
      "Naomi LeDell \u201926 elected UFB chair with 60% of vote in instant runoff",
    abstract: "",
    content:
      '<p>Niyanta Nepal \u201925 was elected president of the Undergraduate Council of Students, the Student Government Association announced on the steps of Faunce House today. Talib Reddick \u201926, who ran unopposed, won the race for vice president.</p>\n<p>Nepal, who ran on a <a href="https://www.browndailyherald.com/article/2024/03/meet-the-2024-ucs-candidates">platform</a> supporting divestment and equitable admissions practices, received 63% of 1,408 votes, defeating current vice president Sarah Frank \u201925. Nearly 10% of voters abstained from the presidential election.&nbsp;</p>\n<p>According to SGA Elections Chair Eli Sporn \u201924, SGA election turnout has declined significantly over the past three years. In 2022, 2,505 students, or 35% of the undergraduate population at the time, voted in runoff elections. In 2023, turnout dropped to 29%, or 2,084 total voters.&nbsp;</p>\n<p>This spring, only 21% of the total undergraduate population, or 1,541 students, voted.&nbsp;</p>\n<p>Current UFB At-Large Representative Naomi LeDell \u201926 will serve as chair of the Undergraduate Finance Board next year. Catherine Jia \u201926 \u2014&nbsp;a former first-year representative and the current UFB press secretary \u2014 will serve as vice chair.&nbsp;</p>\n<p>LeDell received only 30% of 1,207 votes for UFB chair during the first-choice round of the ranked-choice voting scheme. After first-choice votes for the last-place candidate were redistributed to the voters\u2019 second-choice candidates, LeDell received nearly 60% of total votes, securing her the position over <a href="https://www.browndailyherald.com/article/2024/03/justin-bolsen-26-places-second-in-jeopardy-tournament-of-champions">Justin Bolsen</a> \u201926 and current UFB vice chair Ian Kim \u201925.&nbsp;</p>\n<p>Jia won 46.23% of 1,140 total votes for UFB vice chair \u2014&nbsp;just shy of the required majority. After votes were redistributed in the ranked-choice voting process, Jia received 65% of the total, defeating current At-Large Representative Safwan Islam \u201926 for the position.</p>\n<p>According to current UFB&nbsp;Chair Arjun Chopra \u201925, this is the first time in history that two women will lead UFB.&nbsp;&nbsp;</p>\n<p>Jazz Carlson \u201925 and Kelly Wei \u201925 were elected senior co-presidents of the Class Coordinating Board. Carlson and Wei \u2014 the current junior class board president and community outreach officer, respectively \u2014 ran unopposed for the position.</p>\n<p>Nick Lee \u201926 was re-elected president of the 2026 class board, and Ava Stamatakis \u201927 was re-elected president of the 2027 class board. Both candidates ran unopposed.&nbsp;</p>\n<p>Hamza Shahzad \u201927, Leanna Le \u201927, Kieran Lucas \u201926, Alex Pedroza \u201927, Mikael Oberlin \u201925, Christopher Perez \u201927 and Omer Kizil \u201927 were elected UFB at-large representatives.&nbsp;</p>\n<p>For UCS, Maize Cline \u201926 will serve as Chair of Health and Wellness after defeating opponent Neil Stringer \u201927. Rafi Ash \u201926 was elected Treasurer, Tommy Medlin \u201927 will serve as Chair of Student Activities, Kyle Kavully \u201927 will serve as Chair of Campus Life and Willow Stewart \u201926 was elected Chair of Academic Affairs.&nbsp;</p>\n<p>Aside from the presidency and the Chair of Health and Wellness, all positions in UCS were uncontested. Three UCS positions \u2014 including two on the 2026 class board and the Chair of Equity and Inclusion \u2014 remain vacant.</p>\n<p>Sporn said the outcomes of some of the races for UCS were uncertain until today due to an investigation into potential violations of the Elections Handbook. On March 14, two days into the spring elections campaigning period, the Brown Activist Coalition and the Brown Divest Coalition posted a UCS \u201cvoting guide\u201d on Instagram, which listed candidates endorsed by the groups. The post was removed from the site soon after.</p>\n<p>The SGA Elections Handbook prohibits any candidate from \u201ccampaigning on a ticket, which is defined as actively campaigning with another person or group of people with the intention of serving on any branch of student government together.\u201d It also prohibits candidates from endorsing other candidates or using \u201cany Brown Student Activities Organization to promote their candidacy.\u201d</p>\n<p>The guide listed eight names, seven of which were candidates running for positions in UCS, according to Sporn. Of the seven candidates, only two were running for contested positions: Niyanta Nepal \u201925 for UCS president and Maize Cline \u201926 for Chair of Health and Wellness. All seven candidates won their respective elections.</p>\n<p>Jesse Mathis \u201927 \u2014 the eighth name \u2014 was listed as a write-in candidate for UCS Chair of Equity and Inclusion, a position that received no official applications for candidacy. Because roughly 54% of voters abstained from selecting a candidate for this position, Mathis did not win and the position remains vacant.&nbsp;</p>\n<p>\u201cThe Brown Activist Coalition wanted to support candidates who share our values of justice and liberation, and who seemed like they would advocate against the suppression and disregard for student voices by the Brown administration,\u201d coalition spokesperson Ayo Engel-Halfkenny \u201927 wrote in a message to The Herald.&nbsp;</p>\n<p>Engel-Halfkenny explained that \u201cThe guide was created by compiling public information into cohesive Instagram posts.\u201d No candidate, according to Engel-Halfkenny, was involved in the creation of the guide.</p>\n<p>The Elections Board \u2014 composed of Sporn and leaders from each branch of SGA \u2014 was made aware of the voting guide via a complaint, and discussed whether there were \u201cfive or six pretty direct different rule violations that \u2026 are a bit hazy to prove or to justify,\u201d Sporn said.</p>\n<p>The board was specifically concerned with Nepal\u2019s involvement in the creation of the guide, as she is the lead facilitator of the BAC. Nepal wrote in an email to The Herald that she \u201cdid not know about a post going up on Instagram until it was posted.\u201d</p>\n<p>\u201cThe post was taken down because of my request based on concerns that were expressed to me regarding a potential conflict of interest with me facilitating the space and being endorsed,\u201d Nepal wrote. \u201cEven though I had removed myself from this process, I understand the concerns of those who were not actively involved in the BAC conversation.\u201d</p>\n<p>According to Engel-Halfkenny, the voting guide did not violate the Elections Handbook because neither the Activist Coalition nor the Divest Coalition are registered student activities organizations and none of the candidates were involved in its creation.&nbsp;</p>\n<p>Sporn confirmed that the Elections Board has decided not to pursue further action.&nbsp;</p>\n<p>This year, there were no candidates for Student Government Association Elections Chair. Sporn told The Herald that all four vacant positions will be filled by appointment later this semester. All elected candidates will assume their roles in the fall.</p>',
    infobox: null,
    template: null,
    short_token: "abbfa3d28f",
    status: "0",
    weight: "0",
    media_id: "12878",
    created_at: "2024-03-21 23:12:49",
    modified_at: "2024-03-22 04:07:31",
    published_at: "2024-03-22 04:07:17",
    metadata: [],
    hits: "1413",
    normalized_tags: "|18|2123|2525|",
    ceo_id: "48691",
    ssts_rid: null,
    ssts_path: null,
    tags: [
      {
        id: "18",
        uuid: "664812e8-ebcf-481e-9b0c-a48d3024e035",
        name: "University News",
        slug: "university-news",
        metadata: null,
        ceo_id: "9",
      },
      {
        id: "2123",
        uuid: "8a4ede52-e0bf-438d-b2c6-f9e221fbaa41",
        name: "breaking",
        slug: "breaking",
        metadata: null,
        ceo_id: "969",
      },
      {
        id: "2525",
        uuid: "fe2ebacc-4e16-4ba2-9603-0be19e5bbe42",
        name: "homepage",
        slug: "homepage",
        metadata: null,
        ceo_id: "4329",
      },
    ],
    authors: [
      {
        id: "3018",
        uuid: "7b5c3682-0595-4455-8868-8da482833575",
        name: "Julianna Chang",
        email: "",
        slug: "julianna-chang",
        bio: "<p>Julianna Chang is a University News Editor who oversees the academics and advising and student government beats. A sophomore from the Bay Area, Julianna is studying Biology and Political Science on the pre-medical track. When she's not in class or in the office, she can be found eating some type of noodle soup and devouring bad books.</p>",
        tagline: "University News Editor",
        metadata:
          '[{"id":"90ad837c-1554-427a-bcbf-8a4bd381ff85","label":"photo ","value":"https:\\/\\/snworksceo.imgix.net\\/bdh\\/27f2b252-203f-4c2c-9a27-a006bf645bb9.sized-1000x1000.png"}]',
        ceo_id: "3041",
        status: "1",
      },
    ],
    dominantMedia: {
      id: "12878",
      uuid: "924e5b05-3bc3-40a8-8cf2-b128ac2f747f",
      attachment_uuid: "f8033590-01d7-43c2-9eb7-7818df931bf6",
      base_name: "img-0292",
      seo_title: null,
      seo_description: null,
      seo_image: null,
      extension: "jpg",
      preview_extension: "jpg",
      title: "IMG_0292.jpeg",
      content:
        "Nepal, who ran on a platform supporting divestment and equitable admissions practices, received 63% of 1,408 votes",
      source: null,
      click_through: null,
      type: "image",
      height: null,
      width: null,
      status: "0",
      weight: "0",
      created_at: "2024-03-21 23:12:18",
      modified_at: "2024-03-21 23:12:25",
      published_at: "2024-03-21 23:12:19",
      metadata: [],
      hits: "0",
      normalized_tags: "||",
      svg_preview: null,
      ceo_id: "48690",
      ssts_id: null,
      ssts_path: null,
      transcoded: "0",
      authors: [
        {
          id: "3018",
          uuid: "7b5c3682-0595-4455-8868-8da482833575",
          name: "Julianna Chang",
          email: "",
          slug: "julianna-chang",
          bio: "<p>Julianna Chang is a University News Editor who oversees the academics and advising and student government beats. A sophomore from the Bay Area, Julianna is studying Biology and Political Science on the pre-medical track. When she's not in class or in the office, she can be found eating some type of noodle soup and devouring bad books.</p>",
          tagline: "University News Editor",
          metadata:
            '[{"id":"90ad837c-1554-427a-bcbf-8a4bd381ff85","label":"photo ","value":"https:\\/\\/snworksceo.imgix.net\\/bdh\\/27f2b252-203f-4c2c-9a27-a006bf645bb9.sized-1000x1000.png"}]',
          ceo_id: "3041",
          status: "1",
        },
      ],
    },
  },
  {
    id: "35704",
    uuid: "5e80ac68-044d-4e5a-b795-87a2d45b924e",
    slug: "housing-speaker-shekarchi-introduces-15-bill-package-of-housing-bills",
    seo_title: null,
    seo_description: null,
    seo_image: null,
    headline:
      "Housing Speaker Shekarchi introduces 15-bill package of housing bills",
    subhead:
      "Advocates discuss connection between housing production, homelessness",
    abstract: "",
    content:
      '<p>Earlier this month, House Speaker K. Joseph Shekarchi introduced a <a href="https://www.rilegislature.gov/pressrelease/_layouts/15/ril.pressrelease.inputform/DisplayForm.aspx?List=c8baae31-3c10-431c-8dcd-9dbbe21ce3e9&amp;ID=374144">15-bill housing package</a> that seeks to increase housing production rates in Rhode Island. The state has historically ranked <a href="https://www.providencejournal.com/story/news/local/2024/02/07/rhode-island-is-in-a-housing-crisis-it-took-decades-to-get-here/72097387007/">low or last</a> in the country for per-capita new home construction.&nbsp;</p>\n<p>In an email to The Herald forwarded by a spokesperson, Shekarchi described the state\u2019s high housing costs as \u201ca supply and demand issue.\u201d&nbsp;</p>\n<p>\u201cUntil more production at a faster rate occurs, we will continue to see rent and housing prices soar,\u201d he wrote.&nbsp;&nbsp;</p>\n<p>Bill <a href="https://webserver.rilegislature.gov/BillText/BillText24/HouseText24/H7979.pdf">2024-H 7979</a>, according to Shekarchi, would streamline the process of housing development by allowing municipalities to combine their zoning and planning boards. To him, that bill has the most potential to impact Rhode Island\u2019s housing market, especially for smaller communities.&nbsp;</p>\n<p>He additionally highlighted <a href="https://webserver.rilegislature.gov/BillText/BillText24/HouseText24/H7062.pdf">2024-H 7062</a>, which would allow certain kinds of accessory dwelling units to be constructed without requiring discretionary approval. This will \u201cenable homeowners to add additional housing units to Rhode Island\u2019s stock relatively quickly,\u201d Shekarchi wrote.&nbsp;</p>\n<p>Other bills in the package, such as <a href="https://webserver.rilegislature.gov/BillText/BillText24/HouseText24/H7986.pdf">2024-H 7986</a>, seek to expedite the rate at which vacant property is returned to the housing market and additionally allow \u201cthe court to prioritize abatement plans for buyers or receivers who agree that (an) unit will be designated as affordable housing,\u201d according to Shekarchi.&nbsp;</p>\n<p>While not all bills in the package directly incentivize affordable housing, Brenda Clement, executive director of HousingWorks RI, said that limited housing supply has been a major contributor to high prices. \u201cIncreasing supply at different income levels does help affordability,\u201d she added.&nbsp;</p>\n<p>Clement also noted that \u201c<a href="https://turnto10.com/news/local/housingworks-ri-fact-book-affordable-housing-becoming-more-difficult-to-find-rhode-island-apartments-homes-burrillville-central-falls">70%</a> of the projected fastest-growing jobs in the state over the next five years don\u2019t pay anywhere near the wage that you need to afford housing costs and housing prices,\u201d and stressed the need to build more housing at affordable price points.&nbsp;</p>\n<p>Juan Espinoza, spokesperson for the Rhode Island Coalition to End Homelessness, lauded the housing package for attempting to decrease \u201cred tape\u201d limiting housing construction. But he added that due to construction timelines, it\u2019s important to combat the homelessness and housing crises with both short and long-term solutions.</p>\n<p>The coalition\u2019s platform includes support for bills that protect unhoused people, such as the updated <a href="https://www.browndailyherald.com/article/2012/09/r-i-passes-first-homeless-bill-of-rights">Homeless Bill of Rights</a>. According to Espinoza, the updated bill will aid in the enforcement of the 2012 Homeless Bill of Rights.</p>\n<p>Clement highlighted the importance of the $100 million housing bond Governor McKee <a href="https://www.browndailyherald.com/article/2024/01/governor-mckee-unveils-fy-2025-budget">included</a> in his FY 2025 budget to address the housing crisis.&nbsp;</p>\n<p>\u201cThe fact that there is a bond in the state budget of this size is good news,\u201d Clement said. Still, she noted that \u201cit is not enough\u201d and that housing advocates are working to increase the bond amount to $150 million.&nbsp;</p>\n<p>Espinoza added that \u201chousing production has been largely underfunded historically \u2026 and so having <a href="https://www.rilegislature.gov/Special/comdoc/House%20Finance%202024/2-29-2024--H7225--%20Article%205--Question%203--Homes%20RI.pdf">an extra 50 million</a> does help support the system as a whole.\u201d</p>',
    infobox: null,
    template: null,
    short_token: "370b25f1af",
    status: "0",
    weight: "0",
    media_id: "12890",
    created_at: "2024-03-21 21:36:41",
    modified_at: "2024-03-23 19:07:43",
    published_at: "2024-03-22 03:58:39",
    metadata: [],
    hits: "239",
    normalized_tags: "|2|",
    ceo_id: "48681",
    ssts_id: null,
    ssts_path: null,
    tags: [
      {
        id: "2",
        uuid: "e1ecba45-42d1-43b1-b6eb-fd2fd8b7a4d5",
        name: "Metro",
        slug: "metro",
        metadata: null,
        ceo_id: "30",
      },
    ],
    authors: [
      {
        id: "3013",
        uuid: "e20fc2d2-82cc-40cd-908f-37137040baa5",
        name: "Mikayla Kennedy",
        email: "",
        slug: "mikayla-kennedy",
        bio: "<p>Mikayla Kennedy is a Metro editor covering Housing and Transportation. She is a sophomore from New York City studying Political Science and Public Policy Economics. </p>",
        tagline: "Metro Editor",
        metadata: null,
        ceo_id: "3038",
        status: "1",
      },
    ],
    dominantMedia: {
      id: "12890",
      uuid: "60966cdd-f825-4802-9ffb-9e26a789151e",
      attachment_uuid: "724eb827-a856-4be0-bf2e-3bd2a47476f2",
      base_name: "65dad8a9-ebef-4e46-8561-36267dbb69ba-original",
      seo_title: null,
      seo_description: null,
      seo_image: null,
      extension: "jpg",
      preview_extension: "jpg",
      title: "65dad8a9-ebef-4e46-8561-36267dbb69ba.original.jpg",
      content:
        "<p>The state has historically ranked low or last in the country for per-capita new home construction.</p>",
      source: null,
      click_through: null,
      type: "image",
      height: null,
      width: null,
      status: "0",
      weight: "0",
      created_at: "2024-03-22 03:55:59",
      modified_at: "2024-03-22 03:58:27",
      published_at: "2024-03-22 03:55:59",
      metadata: [],
      hits: "0",
      normalized_tags: "||",
      svg_preview: null,
      ceo_id: "48703",
      ssts_id: null,
      ssts_path: null,
      transcoded: "0",
      authors: [
        {
          id: "3012",
          uuid: "4bd221a1-1434-46f4-b8d8-5ceca0c360c9",
          name: "Kaiolena Tacazon",
          email: "",
          slug: "kaiolena-tacazon",
          bio: "<p>Kaiolena Tacazon is the social media chief and a multimedia editor for photo, video and design. She's a sophomore from San Diego studying American Studies and Visual Arts who also works as a photographer for Brown University Athletics. </p>",
          tagline: "Social Media Chief and Multimedia Editor",
          metadata: null,
          ceo_id: "3037",
          status: "1",
        },
      ],
    },
  },
  {
    id: "35703",
    uuid: "ce69e7e7-3af8-461c-98bb-794c40103d50",
    slug: "open-to-everyone-brown-design-workshop-engineers-community-through-trainings-events",
    seo_title: null,
    seo_description: null,
    seo_image: null,
    headline:
      "\u201cOpen to everyone\u201d: Brown Design Workshop engineers community through trainings, events",
    subhead:
      "Workshop run by full-time engineering staff, student monitors, managers",
    abstract: "",
    content:
      '<p>Brown Design Workshop, located in Barus and Holley, is a student-run maker space open to all Brown and RISD students, as well as Providence residents. The space is run by full-time engineering staff, as well as student monitors and managers who lead all of its workshops.</p><p>\u201cWe welcome everyone and really want to build a community of makers,\u201d said Angela Baek \u201924, a monitor at the BDW.</p><p>While \u201cthe Brown Design Workshop is used a lot by particularly engineering, visual art and architecture students at Brown,\u201d the BDW is working to \u201cpublicize to everyone who wants to build,\u201d said BDW Monitor Arjun Khurana \u201925.&nbsp;</p><p>The BDW runs skill-based <a href="https://www.browndesignworkshop.org/calendar">workshops</a> for students, which are offered on a first-come first-serve basis with no registration required. According to Baek, workshops range \u201cfrom more standard ones like sewing and woodworking to advanced classes like,\u201d computer numerical control.&nbsp;&nbsp;</p><p>Workshops are given on weekdays at every even hour between 12 p.m. and 10 p.m.. Popular sessions such as laser-cutting, sewing and 3D printing are offered every week.</p><p>\u201cAll of our workshops are open to everyone. You don\u2019t need any past experiences to join,\u201d Baek said.</p><p>After attending workshops on specific skills, students receive a sticker on their ID cards \u2014 which they receive the first time they visit the BDW \u2014 that allows them to freely use the BDW\u2019s maker space and related tools.</p><p>\u201cOur 3D printers and laser cutters are usually at work at all hours, because students often use them for different classes or even for making toys,\u201d BDW Manager Caroline Kaleel \u201924 said. She added that students are also encouraged to navigate their interests by using the material circulation station, where samples and pieces are organized based on material type.</p><p>The BDW currently collaborates with both on-campus clubs as well as schools in the greater Providence area.&nbsp;</p><p>\u201cWe host one-time workshops and provide materials for <a href="https://www.brownuswe.org/">Brown Society of Women Engineers</a>, <a href="https://www.instagram.com/brownformularacing/">Formula Racing</a>, <a href="https://studentactivities.brown.edu/organizations/art-service">Art for Service</a> and <a href="https://www.browndailyherald.com/article/2024/03/women-build-at-brown-breaks-down-barriers-in-the-brown-design-workshop">Women Build at Brown</a>,\u201d said Chloe Chow \u201926, another monitor at BDW.&nbsp;</p><p>A small group of students from the Lincoln School additionally \u201ccome in once a week to learn woodworking, metals and 3D printing with our monitors,\u201d said Manager Serena Vu \u201925. Students come to the BDW as part of their Introduction to Engineering classes and end the class by creating bio-inspired medical devices for their final project.&nbsp;</p><p>High school students from the charter school Blackstone Academy also take their elective classes at the BDW, where they learn to use workshop tools for a community-impact project meant to benefit Blackstone or the public.</p><p>Moving forward, the BDW aims to increase engagement with the greater Providence community. It currently works to do so through passing out brochures and giving tours to non-Brown students. \u201cWe want to increase connections both in terms of reach and more intimate collaborations with other maker spaces,\u201d said Baek.&nbsp;</p><p>The managers also expect to initiate more projects and programs within the BDW.</p><p>BDW managers hope that the mending program, a project that they are bringing back, will bring more newcomers to the space. As part of the program, BDW monitors assist students in fixing anything they\u2019d like.</p><p>\u201cThere aren\u2019t many spaces on campus where hands-on learning is valued, so we really want to bring in more students where they can channel their creative outlet with their hands,\u201d Manager Amick Sollenberger \u201924 said.&nbsp;</p><p>The BDW also hopes to increase sustainability in 2024 by promoting the reuse of typically discarded or scrap materials. \u201cWe are pushing for recycling for 3D printer filaments and using offcuts from wood projects for new projects,\u201d Khurana said.</p><p>\u201cSo many projects have come up every year since I started at the Brown Design Workshop,\u201d Baek said. \u201cThere\u2019s always new machines that we acquire, and everyone feels some initiative to start something new.\u201d</p><p>\u201cI\u2019m excited to see what the monitors in training can come up with in terms of new ways to engage with tools and host workshops after this semester,\u201d Baek added.</p>',
    infobox: null,
    template: null,
    short_token: "14cd42e535",
    status: "0",
    weight: "0",
    media_id: "12884",
    created_at: "2024-03-21 21:36:09",
    modified_at: "2024-03-22 03:47:51",
    published_at: "2024-03-22 03:47:48",
    metadata: [],
    hits: "318",
    normalized_tags: "|18|",
    ceo_id: "48680",
    ssts_id: null,
    ssts_path: null,
    tags: [
      {
        id: "18",
        uuid: "664812e8-ebcf-481e-9b0c-a48d3024e035",
        name: "University News",
        slug: "university-news",
        metadata: null,
        ceo_id: "9",
      },
    ],
    authors: [
      {
        id: "3124",
        uuid: "4c0097c2-7802-4e09-a0f8-fc2394c91e67",
        name: "Rebecca Weng",
        email: "",
        slug: "rebecca-weng",
        bio: "<p>Rebecca Weng is a Senior Staff Writer for Arts and Culture. She is a freshman from Guangzhou, China studying English and CS-Econ.</p>",
        tagline: "Senior Staff Writer",
        metadata: null,
        ceo_id: "3155",
        status: "1",
      },
    ],
    dominantMedia: {
      id: "12884",
      uuid: "ab6dfcef-ae95-4cd1-af18-b56f53825319",
      attachment_uuid: "477d9869-f1bc-4720-bb1a-b283fc4ed77c",
      base_name: "courtesyofangelabaek",
      seo_title: null,
      seo_description: null,
      seo_image: null,
      extension: "jpg",
      preview_extension: "jpg",
      title: "Weng_BDW_CO_AngelaBaek.jpeg",
      content:
        "After attending workshops on specific skills, students will get a sticker on their ID cards, which allows them to freely use the BDW\u2019s makerspace and related tools.\nPhoto Courtesy of Angela Baek.",
      source: null,
      click_through: null,
      type: "image",
      height: null,
      width: null,
      status: "0",
      weight: "0",
      created_at: "2024-03-22 01:24:02",
      modified_at: "2024-03-22 01:24:38",
      published_at: "2024-03-22 01:24:02",
      metadata: [],
      hits: "0",
      normalized_tags: "||",
      svg_preview: null,
      ceo_id: "48698",
      ssts_id: null,
      ssts_path: null,
      transcoded: "0",
      authors: [],
    },
  },
  {
    id: "35710",
    uuid: "605a3a49-7686-4255-aeb1-b59b303eba59",
    slug: "district-maintains-360-hs-closure-plans-after-ppsd-board-votes-to-halt-decision",
    seo_title: null,
    seo_description: null,
    seo_image: null,
    headline:
      "District maintains 360 HS closure plans after PPSD board votes to halt decision",
    subhead: "Closure continues to spark resistance, legislative efforts",
    abstract: "",
    content:
      '<p>This Wednesday, the Providence Public School Board unanimously passed a <a href="https://providencepublic.ic-board.com/Attachments/32f8a614-6c87-458b-8748-1b9a692a8694.pdf">resolution</a> calling on the Providence Public School District and the Rhode Island Department of Education to halt <a href="https://www.browndailyherald.com/article/2024/02/360-high-school-to-close-merge-under-jsecs-william-b-cooley-sr-hs">the decision to close</a> 360 High School and merge it under the Juanita Sanchez Educational Complex\u2019s new Life Sciences Institute.&nbsp;</p>\n<p>But PPSD, which is controlled by the state, still plans to restructure 360 by merging it into JSEC, according to PPSD spokesperson Jay Wegimont, who acknowledged the School Board\u2019s advisory role in an email to The Herald.</p>\n<p>The closure of 360 has been contested since it was announced on Feb. 6. The day after its announcement, students organized a walkout in opposition to the decision, The Herald <a href="https://www.browndailyherald.com/article/2024/02/360-high-school-to-close-merge-under-jsecs-william-b-cooley-sr-hs">previously reported</a>. PPSD and RIDE meetings have been <a href="https://www.browndailyherald.com/article/2024/02/360-high-school-community-pushes-to-stop-school-closure-at-ride-meeting">dominated</a> by 360 community members seeking to keep their school open.&nbsp;</p>\n<p>PPSD has been under state takeover since 2019. As a result, the School Board does not have decision-making authority regarding school closures. \u201cUnder the state intervention, the school board serves in an advisory capacity,\u201d wrote RIDE\u2019s Director of Communications Victor Morente in an email to The Herald.&nbsp;</p>\n<p>Local representatives have also responded to the closure by proposing new legislation regulating school closure decisions and other issues of district decision-making.</p>\n<p><b>School Board resolution&nbsp;</b></p>\n<p>The School Board resolution called on RIDE and PPSD to halt the 360 closure decision and expressed concern about both \u201cthe lack of transparency\u201d in the decision-making process and the disruption to student lives the closure may cause.</p>\n<p>\u201cThe Providence School Board vehemently opposes the closure or merger of 360 High School and strongly urges the exploration of alternative measures to sustain its continued operation,\u201d the resolution stated.</p>\n<p>\u201cWe want transparency about the whole process,\u201d said Christian Martinez, a 360 math teacher and PPSD graduate, in an interview with The Herald after the Feb. 27 RIDE meeting. \u201cWe want clarity, (and) we want answers (justifying the merger) that actually match with the real data.\u201d&nbsp;</p>\n<p>At the Wednesday meeting, Superintendent Javier Monta\u00f1ez reiterated that the decision to merge 360 under JSEC is final. Board Member Anjel Newmann responded by stating that \u201cthere\u2019s still time to be responsive to our community.\u201d</p>\n<p>\u201cPPSD leadership closely reviewed 360\u2019s performance data and made a recommendation for the merger to the Commissioner of Education, who has the authority to effectuate the merger under the Crowley Act,\u201d wrote RIDE spokesperson, in an email to The Herald.</p>\n<p>Morente noted that the PPSD leadership who made the merger recommendation included Monta\u00f1ez and \u201c<a href="https://www.providenceschools.org/Page/5867">his leadership team.</a>\u201d</p>\n<p>Wegimont noted that the Juanita Sanchez Life Sciences Institute has extended 21 job offers to teachers, 15 of which were made to <a href="https://www.browndailyherald.com/article/2024/03/over-350-providence-public-school-district-teachers-displaced-layoffs-possible">displaced 360 teachers</a>. He added that \u201cstudent placement from 360 High School is underway and so far, only 14 students have asked to be assigned\u201d to a school other than JSEC.</p>\n<p><b>District reasoning behind the closure</b></p>\n<p>In his email to The Herald, Morente cited low performance and cost concerns as motives for the closure. He added that RIDE believes the new Juanita Sanchez Life Sciences Institute \u2014 which 360 is being merged into \u2014 \u201ccentered students\u2019 needs and prioritized expanding access to innovative and engaging programming for in-demand, high-paying fields.\u201d</p>\n<p>\u201cThe restructuring proposes to answer calls from students for greater academic opportunity and more engaging programming that will set them up for success in college, career and beyond,\u201d Morente wrote.&nbsp;</p>\n<p>He noted that information regarding the closure was \u201cleaked\u201d before a scheduled session for teachers could occur. \u201cThe school principal was also aware that restructuring was a consideration,\u201d he wrote.</p>\n<p>According to Dr. Ellen Foley, a STEM learning facilitator at 360 and former associate director of the Annenberg Institute, 360 students were scheduled to take the current academic year\u2019s proficiency exams in April. The scores of these exams would decide whether 360 could be moved out of one-star status, which is being used to justify the merger with JSEC, Foley said in an interview with The Herald.</p>\n<p>Ryan Barker, a 360 social studies teacher, said at the Feb. 27 RIDE meeting that 360 is very close to moving up from one-star status. \u201cIt\u2019s not like 360 is far from two-star status,\u201d he said. \u201cWe need one or two students to demonstrate proficiency on the SAT to move up \u2014 what other school could claim such a narrow margin?\u201d</p>\n<p>The SAT determines a school\u2019s achievement and growth rating and is only offered in English. 360 High School has the second-highest <a href="https://reportcard.ride.ri.gov/202223/SchoolProfile?SchCode=28195&amp;DistCode=28">percentage</a> of multilingual learners in the district, and community members have said this negatively impacts their star status. Morente did not respond to a specific request for comment about how RIDE accounts for high percentages of multilingual learners in proficiency rates.&nbsp;</p>\n<p>Morente did not directly address why the district did not wait until after April to decide the future of 360. But, he emphasized that \u201c360 High School has been identified for Comprehensive Support and Improvement (CSI) since 2019-2020, and did not meet the exit criteria for 2023-2024.\u201d&nbsp;</p>\n<p>The district has not determined exact staffing numbers for the newly merged school, The Herald <a href="https://www.browndailyherald.com/article/2024/02/360-high-school-to-close-merge-under-jsecs-william-b-cooley-sr-hs">previously reported</a>. Morente wrote that \u201cthe District will continue to closely monitor its budget as it considers staffing.\u201d</p>\n<p>Foley told The Herald that it\u2019s unclear how much money the merger will save. She added that 360\u2019s per pupil expenditure is <a href="https://reportcard.ride.ri.gov/202223/SchoolProfile?SchCode=28195&amp;DistCode=28">lower</a> than the state average. The JSEC school that 360 is being merged with spends <a href="https://reportcard.ride.ri.gov/202223/SchoolProfile?SchCode=28189&amp;DistCode=28">nearly double</a> per student compared to 360.&nbsp;</p>\n<p>\u201cThe District will realize $1.5-2 (million) in cost savings from the restructuring,\u201d wrote Morente. He did not explain specifically where those savings are coming from.&nbsp;</p>\n<p><b>Representatives respond with legislation</b></p>\n<p>Rhode Island District 7 Representative David Morales introduced <a href="https://webserver.rilegislature.gov/BillText24/HouseText24/H7726.pdf">legislation</a> that regulates the process behind school restructuring decisions. The legislation requires meetings with students and parents, public forums in large venues about closure or merger proposals, contingency plans for impacted staff and detailed transition planning for school buildings and displaced students.&nbsp;</p>\n<p>Morales told The Herald that the legislation aims to ensure transparency throughout the decision-making process.</p>\n<p>\u201cYou can\u2019t just come in and say \u2018We\u2019re going to close your school at the end of the year,\u2019\u201d Morales said. \u201cThere has to be a process that is followed before it is ever made official.\u201d&nbsp;</p>\n<p>The legislation would be required for all school districts, including those under state takeover.</p>\n<p>In the House Committee on Education\u2019s March 13 <a href="https://capitoltvri.cablecast.tv/show/8921?site=1">meeting</a>, Morales said that he was open to modifying the bill for districts that already engage the community in their decision-making processes.</p>\n<p>At the meeting, several 360 community members attended to show their support for the bill. \u201cThe way (how) this all transpired was just wrong,\u201d said Daisy Vega, a 360 school counselor, in a comment at the meeting. \u201cIt didn\u2019t include any of us.\u201d</p>\n<p>School Board member Night Jean Muhingabo also expressed his support for the bill at the March 13 meeting. He addressed 360\u2019s closure, alongside two elementary schools that closed in 2022 and a middle school that is being phased out.</p>\n<p>\u201cAs a board member, I was surprised to learn about these closure plans on Twitter, and RIDE didn\u2019t hold any meetings with the School Board,\u201d Muhingabo said. \u201cWe need transparency.\u201d</p>\n<p>Morales also introduced <a href="https://webserver.rilegislature.gov/BillText24/HouseText24/H7614.pdf">legislation</a> to make the student representative on the Council on Elementary and Secondary Education a voting member. \u201cHaving a voting member in the form of a student on the K-12 Council gives (them) an opportunity to further advocate, instead of being a passive listener,\u201d he said.</p>\n<p>Several community members voiced support for the bill at the March 6 House Committee on Education <a href="https://capitoltvri.cablecast.tv/show/300?site=1">meeting</a>.</p>\n<p>\u201cWe believe as members of a democracy, students should be prepared to participate,\u201d Dexter Vincent, Co-Director of the Leadership Team for the Providence Student Union and a senior at Classical High School, said at the meeting. \u201cI urge the committee members to pass this bill.\u201d R.I. Kids Count also expressed support for the bill.&nbsp;</p>\n<p>Morente did not respond to a request for comment about whether RIDE would support either piece of legislation.</p>',
    infobox: null,
    template: null,
    short_token: "e3bb71ee73",
    status: "0",
    weight: "0",
    media_id: "12891",
    created_at: "2024-03-21 21:42:45",
    modified_at: "2024-03-22 04:16:32",
    published_at: "2024-03-22 03:04:00",
    metadata: [],
    hits: "420",
    normalized_tags: "|2|2525|",
    ceo_id: "48688",
    ssts_id: null,
    ssts_path: null,
    tags: [
      {
        id: "2",
        uuid: "e1ecba45-42d1-43b1-b6eb-fd2fd8b7a4d5",
        name: "Metro",
        slug: "metro",
        metadata: null,
        ceo_id: "30",
      },
      {
        id: "2525",
        uuid: "fe2ebacc-4e16-4ba2-9603-0be19e5bbe42",
        name: "homepage",
        slug: "homepage",
        metadata: null,
        ceo_id: "4329",
      },
    ],
    authors: [
      {
        id: "3103",
        uuid: "bd195059-21c9-44b4-8d27-d8cfc6cfad87",
        name: "Ciara Meyer",
        email: "",
        slug: "ciara-meyer",
        bio: "<p>Ciara Meyer is a Senior Staff Writer covering the Beyond Brown beat. She is from Saratoga Springs, New York and plans on concentrating in Statistics and English nonfiction. In her free time, she loves scrapbooking and building lego flowers.</p>",
        tagline: "Senior Staff Writer",
        metadata: null,
        ceo_id: "3130",
        status: "1",
      },
    ],
    dominantMedia: {
      id: "12891",
      uuid: "8ccdcbdc-1eca-4a17-a3e7-1f77f8301d3e",
      attachment_uuid: "1e8a85d8-9bfc-4c62-883a-6acd0c12524e",
      base_name: "360-update-lilly-nguyen-already-on-bdh-site",
      seo_title: null,
      seo_description: null,
      seo_image: null,
      extension: "jpg",
      preview_extension: "jpg",
      title: "360 Update - Lilly Nguyen (already on bdh site).jpg",
      content:
        "Local representatives have also responded to the closure by proposing new legislation regulating school closure decisions and other issues of district decision-making.",
      source: null,
      click_through: null,
      type: "image",
      height: null,
      width: null,
      status: "0",
      weight: "0",
      created_at: "2024-03-22 04:14:20",
      modified_at: "2024-03-22 04:15:18",
      published_at: "2024-03-22 04:14:20",
      metadata: [],
      hits: "0",
      normalized_tags: "||",
      svg_preview: null,
      ceo_id: "48704",
      ssts_id: null,
      ssts_path: null,
      transcoded: "0",
      authors: [
        {
          id: "106",
          uuid: "e060a3e8-7037-4106-8b64-a0a52ba7b2a3",
          name: "Lilly Nguyen",
          email: "",
          slug: "lilly-nguyen",
          bio: "<p>Lilly Nguyen is a photographer for the Herald. She is a freshman concentrating in neuroscience. In her free time, Lilly loves to sew and blast Lana Del Rey for the entire floor.</p>",
          tagline: "",
          metadata: null,
          ceo_id: "119",
          status: "1",
        },
      ],
    },
  },
  {
    id: "35706",
    uuid: "70d70ee1-4204-4354-8281-afdb74e4abf7",
    slug: "glo-files-federal-labor-complaint-against-university-alleges-retaliatory-threat",
    seo_title: null,
    seo_description: null,
    seo_image: null,
    headline:
      "GLO files federal labor complaint against University, alleges \u201cretaliatory threat\u201d",
    subhead:
      "Complaint responds to March 11 announcement regarding protest policies",
    abstract: "",
    content:
      '<p>On March 12, the Graduate Labor Organization filed a federal Unfair Labor Practices complaint, alleging that the University made a \u201cretaliatory threat\u201d of discipline against the union\u2019s members.</p>\n<p>The complaint was filed a day after the University <a href="https://today.brown.edu/announcements/171022">announced</a> its updated <a href="https://www.brown.edu/about/administration/provost/communications/faq-freedom-expression-protest-and-related-policies">FAQ on protests</a>, which included a new section describing policies on activism by labor unions.&nbsp;</p>\n<p>\u201cAs is its right, the University expects unions and their leaders and members, when conducting protests and demonstrations advancing a political or other type of opinion on matters unrelated to their employment, to abide by Brown policies including those related to the use of University spaces,\u201d the updated FAQ reads. \u201cIf a union-sponsored event does not comply with University rules, that union\u2019s leadership and/or members can be held accountable for failing to follow University policies.\u201d</p>\n<p>The FAQ further states that \u201cAny member of the Brown community organizing a protest on University property (including the College Green) must reserve the space in which the protest will take place, and recognized student organizations must register any event where 50 or more attendees are anticipated.\u201d</p>\n<p>Provost Francis J. Doyle III wrote in a campus-wide email that the University wanted to \u201cprovide additional guidance related to protest activity by labor unions on campus, particularly given recent visibility about planned activism by some union leaders on campus this spring.\u201d&nbsp;</p>\n<p>In an interview with The Herald, GLO President Sherena Razek GS characterized the message as a \u201cvery clearly a thinly-veiled retaliatory threat to actions that the Palestine Solidarity Caucus has been taking over the past several months,\u201d as well as a retaliatory threat to actions of GLO and other labor organizations.&nbsp;</p>\n<p>The university-wide email came three days after the GLO-affiliated Palestine Solidarity Caucus held a <a href="https://www.browndailyherald.com/article/2024/03/group-of-brown-university-tour-guides-picket-for-coordinator-dismissed-following-slack-message">rally</a> for International Working Women\u2019s Day and for a demoted tour coordinator.</p>\n<p>Neither GLO nor PSC register protests with the University, according to Razek.&nbsp;</p>\n<p>The union filed the complaint with the National Labor Relations Board, the federal agency that \u201cinvestigates and remedies\u201d unfair labor practices under the National Labor Relations Act.&nbsp; NLRB Spokesperson Kayla Blado confirmed in an email to The Herald that \u201cthe NLRB\u2019s Region 1-Boston office received the charge and is currently investigating it.\u201d</p>\n<p>In an email to The Herald, University spokesperson Brian Clark wrote that the University sent the email to \u201coffer clarity\u201d amid planned protests.&nbsp;</p>\n<p>\u201cWe\u2019ve seen public statements from some unions about planned protest activity, and we\u2019ve come across misunderstandings in some conversations in regard to whether individuals who are union members are accountable to University policies when engaged in protest and demonstrations,\u201d Clark wrote.&nbsp;</p>\n<p>\u201cIndividuals are not absolved from abiding by Brown policies by virtue of union membership,\u201d Clark added.&nbsp;</p>\n<p>The University\u2019s decision to send the email was also prompted in part by the fact that \u201cmultiple members of the Brown community, specifically members of labor unions on campus, have reached out directly to university leaders,\u201d according to Clark.</p>\n<p>\u201cSome have sought clarity on these questions. Others have expressed concerns about specific union activities they felt extended beyond the purview of those unions,\u201d Clark wrote.&nbsp;</p>\n<p>Razek, among other GLO leaders, argues that the union\u2019s actions <a href="https://www.browndailyherald.com/article/2024/02/announcement-came-at-mid-hunger-strike-rally">calling</a> on the University to divest its endowment from \u201cwar crimes and atrocities in Palestine or anywhere else\u201d constitute \u201cprotected activity\u201d under federal labor law because those are \u201cemployment-related\u201d matters.&nbsp;</p>\n<p>\u201cThe way in which the wealth generated from our labor is invested in war crimes and atrocities in Palestine or anywhere else in the world is absolutely part of our working conditions,\u201d she said.</p>\n<p>The University did not specify whether its guidance responded to specific protests or issues.</p>',
    infobox: null,
    template: null,
    short_token: "5e21437038",
    status: "0",
    weight: "0",
    media_id: "12883",
    created_at: "2024-03-21 21:38:02",
    modified_at: "2024-03-22 04:04:56",
    published_at: "2024-03-22 03:03:00",
    metadata: [],
    hits: "633",
    normalized_tags: "|18|2525|",
    ceo_id: "48683",
    ssts_id: null,
    ssts_path: null,
    tags: [
      {
        id: "18",
        uuid: "664812e8-ebcf-481e-9b0c-a48d3024e035",
        name: "University News",
        slug: "university-news",
        metadata: null,
        ceo_id: "9",
      },
      {
        id: "2525",
        uuid: "fe2ebacc-4e16-4ba2-9603-0be19e5bbe42",
        name: "homepage",
        slug: "homepage",
        metadata: null,
        ceo_id: "4329",
      },
    ],
    authors: [
      {
        id: "3126",
        uuid: "31f1e9a3-c1bb-4ca9-9df1-56c7b33e91c4",
        name: "Ethan Schenker",
        email: "",
        slug: "ethan-schenker",
        bio: "<p>Ethan Schenker is a Senior Staff Writer covering staff and student labor. He is from Bethesda, MD, and plans to study International and Public Affairs and Economics. In his free time, he enjoys playing piano and clicking on New York Times notifications. </p>",
        tagline: "Senior Staff Writer",
        metadata: null,
        ceo_id: "3157",
        status: "1",
      },
    ],
    dominantMedia: {
      id: "12883",
      uuid: "8d00ef81-5072-4f91-835b-3d0232206fb2",
      attachment_uuid: "6a6902e3-6973-4158-b652-ad33061f1008",
      base_name: "schenker-glo-co-dana-richie",
      seo_title: null,
      seo_description: null,
      seo_image: null,
      extension: "jpg",
      preview_extension: "jpg",
      title: "Schenker_GLO_CO_Dana_Richie.jpg",
      content:
        "The complaint was filed a day after the University released a Today@Brown announcement on its updated FAQ on protests with a new section describing policies on activism by labor unions. ",
      source: null,
      click_through: null,
      type: "image",
      height: null,
      width: null,
      status: "0",
      weight: "0",
      created_at: "2024-03-22 01:20:21",
      modified_at: "2024-03-22 01:22:20",
      published_at: "2024-03-22 01:20:21",
      metadata: [],
      hits: "0",
      normalized_tags: "||",
      svg_preview: null,
      ceo_id: "48696",
      ssts_id: null,
      ssts_path: null,
      transcoded: "0",
      authors: [
        {
          id: "2793",
          uuid: "e491286a-c7cd-4cf4-a6b5-90de5050f898",
          name: "Dana Richie",
          email: "",
          slug: "dana-richie",
          bio: "<p>\u200b\u200bDana Richie is a senior staff writer for Arts and Culture and the photo chief. She enjoys using multiple forms of media to capture peoples\u2019 stories and quirks. In her free time, she loves knitting, learning about local history and playing ultimate frisbee. </p>",
          tagline: "Senior Staff Writer",
          metadata: null,
          ceo_id: "2806",
          status: "1",
        },
      ],
    },
  },
];
