name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Redis
        run: sudo apt-get update && sudo apt-get install -y redis-server

      - name: Install dependencies
        run: npm install
        working-directory: ./backend/nms

      - name: Run Jest tests
        run: npm test
        working-directory: ./backend/nms

      - name: Run Playwright tests
        run: npm run test:pw
        working-directory: ./backend/nms
